# Generated by Django 5.0.3 on 2024-05-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('map_url', models.CharField(max_length=250)),
                ('img_url', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('seats', models.CharField(max_length=250)),
                ('has_toilet', models.BooleanField()),
                ('has_wifi', models.BooleanField()),
                ('has_sockets', models.BooleanField()),
                ('can_take_calls', models.BooleanField()),
                ('coffee_price', models.CharField(max_length=250)),
            ],
        ),
    ]
