# Generated by Django 5.0.3 on 2024-05-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('domain', models.CharField(choices=[('IT', 'IT'), ('Non-IT', 'Non_IT')], max_length=100)),
                ('active', models.BinaryField(default=True)),
            ],
        ),
    ]
