# Generated by Django 5.0.3 on 2024-05-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='added_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
